// SPDX-License-Identifier: Apache-2.0

// The generated OpenAPI types for the Spellguard management API — the single
// types source of truth for every TypeScript consumer (plugins, dashboard, and
// later the verifier).
//
// Source of truth: packages/management/openapi.json → openapi-typescript.
// Regenerated by `pnpm run gen:clients` and by the dev type-watcher
// (packages/management/scripts/watch-types.mjs).
//
// PURE TYPES — this package has no runtime and no build step. Always import as
// `import type { paths } from '@spellguard/management-api-types'`; the import is
// erased at build, so consumers' bundlers (esbuild for the plugins, Vite for the
// dashboard) inline nothing and the package is safe in every environment.
export type { paths, components, operations } from './generated/schema';
