# SPDX-License-Identifier: Apache-2.0

"""
spellguard_ctls - Attestation Document Generation

Server-side generation of Verifier attestation documents.
"""

from __future__ import annotations

import hashlib
import os
import time

from ..crypto.ephemeral import get_session_public_key, sign_with_session_key
from ..types import VerifierAttestationDocument


async def generate_attestation_document(
    nonce: str,
) -> VerifierAttestationDocument:
    """Generate a Verifier self-attestation document.

    In production (Phala Cloud, etc.):
    - image_hash comes from the reproducible Docker build
    - hardware_signature is generated by Verifier hardware (Intel SGX/TDX)

    In mock mode:
    - image_hash is from environment variable
    - hardware_signature is self-signed (for development only)

    Args:
        nonce: Client-provided nonce to prevent replay attacks.

    Returns:
        Attestation document.

    Raises:
        RuntimeError: If session keys are not initialized or VERIFIER_IMAGE_HASH is not set.
    """
    image_hash = get_expected_image_hash()
    public_key = get_session_public_key()

    if not public_key:
        raise RuntimeError("Session keys not initialized")

    timestamp = int(time.time() * 1000)

    # Data to sign: imageHash || publicKey || timestamp || nonce
    data_to_sign = "|".join([image_hash, public_key, str(timestamp), nonce])
    data_bytes = data_to_sign.encode("utf-8")

    # In mock mode, self-sign. In production, this would be signed by Verifier hardware.
    is_mock_mode = os.environ.get("VERIFIER_MOCK_MODE") == "true"

    event_log: str | None = None
    compose_hash: str | None = None

    if is_mock_mode:
        hardware_signature = await sign_with_session_key(data_bytes)
    else:
        # Production: get a real TDX quote from Phala's dstack Guest Agent.
        # The dstack socket (/var/run/dstack.sock) must be mounted in the container.
        # Note: This requires the phala dstack-sdk Python package to be installed.
        try:
            from dstack_sdk import DstackClient  # type: ignore[import-untyped]

            client = DstackClient()

            # Hash the attestation data -- getQuote accepts report_data up to 64 bytes
            data_hash = hashlib.sha384(data_bytes).digest()
            quote_result = client.get_quote(data_hash)

            hardware_signature = quote_result.quote  # hex-encoded TDX quote
            event_log = getattr(quote_result, "event_log", None)

            # Retrieve compose hash from CVM info if available
            info = client.info()
            tcb_info = getattr(info, "tcb_info", None)
            if tcb_info and hasattr(tcb_info, "compose_hash"):
                compose_hash = tcb_info.compose_hash
        except ImportError:
            raise RuntimeError(
                "dstack-sdk is required for production Verifier attestation. "
                "Set VERIFIER_MOCK_MODE=true for development."
            )

    return VerifierAttestationDocument(
        image_hash=image_hash,
        hardware_signature=hardware_signature,
        public_key=public_key,
        timestamp=timestamp,
        nonce=nonce,
        supported_algorithms=["AES-256-GCM", "ChaCha20-Poly1305", "Ed25519"],
        event_log=event_log,
        compose_hash=compose_hash,
    )


def get_expected_image_hash() -> str:
    """Get the expected image hash for verification.
    Requires VERIFIER_IMAGE_HASH environment variable to be set.

    Returns:
        The Verifier image hash string.

    Raises:
        RuntimeError: If VERIFIER_IMAGE_HASH is not set.
    """
    hash_val = os.environ.get("VERIFIER_IMAGE_HASH")
    if not hash_val:
        raise RuntimeError(
            "VERIFIER_IMAGE_HASH environment variable is required. "
            "Set it to the SHA384 hash of the Verifier Docker image."
        )
    return hash_val


def compute_image_hash(image_contents: bytes) -> str:
    """Compute image hash from Docker image contents.

    Args:
        image_contents: Raw bytes of the Docker image.

    Returns:
        SHA384 hash string prefixed with 'sha384:'.
    """
    hash_bytes = hashlib.sha384(image_contents).digest()
    return f"sha384:{hash_bytes.hex()}"
