// SPDX-License-Identifier: Apache-2.0

/**
 * Disk-persisted credential store for the OpenClaw Spellguard plugin.
 *
 * Mirrors the shape of `packages/claude-code-plugin/src/lib/config-store.ts`
 * but lives under `~/.config/spellguard-openclaw/` so a single operator
 * machine running both the Spellguard plugin and an OpenClaw bot never
 * confuses the two identities.
 *
 * The store is the on-disk truth for:
 *   - `agentId`        — UUID generated by the setup CLI before first connect
 *   - `agentSecret`    — long-lived bearer minted at bootstrap
 *   - `scopedToken`    — latest provider credential (e.g., GitHub installation
 *                        token); refreshed by the live socket
 *   - `lastServerSeq`  — durability cursor for resume on reconnect
 *
 * POSIX 0600. The plugin refuses to read a world-readable file.
 *
 * Writes are symlink-safe and atomic:
 *   - We `lstat` the target first and refuse to write if it is a symlink.
 *   - We write to a temp sibling opened with `O_NOFOLLOW | O_EXCL | O_WRONLY
 *     | O_CREAT`, `fchmod(0o600)` after open, `fsync`, then `rename()` over
 *     the target. This defeats a same-user attacker who pre-places a symlink
 *     at the store path pointing at e.g. `~/.ssh/authorized_keys`, and
 *     ensures the mode is reasserted to 0o600 even when the target file
 *     already exists with a looser mode.
 */

import { randomBytes } from 'node:crypto';
import {
  closeSync,
  existsSync,
  fchmodSync,
  constants as fsConstants,
  fsyncSync,
  lstatSync,
  mkdirSync,
  openSync,
  readFileSync,
  renameSync,
  statSync,
  unlinkSync,
  writeFileSync,
  writeSync,
} from 'node:fs';
import { platform } from 'node:os';
import { basename, dirname, join } from 'node:path';
import { credentialStorePath } from './credential-store-paths';

export interface ProviderCredEntry {
  kind: 'issued' | 'manual' | 'auto-created' | 'provisioned';
  credentialId: string;
  secrets: Record<string, string>;
  scopedToken?: string;
  scopedTokenId?: string;
  expiresAt?: string;
  scopeSummary?: { repos: string[] };
  gitAuthorName?: string;
  gitAuthorEmail?: string;
  /** Phase C: the GitHub App installation id backing a github entry. */
  installationId?: number;
  revoked?: boolean;
}

export interface CredentialStore {
  agentId: string;
  agentSecret: string;
  /** Legacy single-provider fields — present on GitHub-issued stores. */
  scopedToken?: string;
  scopedTokenId?: string;
  expiresAt?: string;
  scopeSummary?: { repos: string[] };
  spellguardBaseUrl: string;
  /** Bootstrap-frame author identity for git commit signing. */
  gitAuthorName?: string;
  gitAuthorEmail?: string;
  /** Set true when the server emits `credential_revoked`. */
  revoked?: boolean;
  /** Durability cursor — decimal string (uint64). */
  lastServerSeq?: string;
  /**
   * CR-003: cached known-credentials projection, echoed in the reconnect
   * `Resume.known_credentials`. Without persisting this, every gateway
   * restart reconnects with `known_credentials: []`, which the broker's
   * divergence detector reads as a stale client and re-delivers every
   * credential — causing a redundant gateway restart per reconnect (the
   * double-restart on credential delivery). Mirrors the sibling
   * claude-code-plugin daemon's `config-store.ts` field.
   */
  knownCredentials?: Array<{ provider: string; scoped_token_id: string }>;
  /** Bootstrap-frame agent-name echo for dashboard display. */
  agentName?: string;
  /**
   * Provider-agnostic credential map. Populated by back-compat shim for legacy
   * stores.
   *
   * Phase C (Task 7): GitHub credentials are keyed PER ORG as
   * `github:<orgLoginLower>` so one machine can hold N GitHub credentials (one
   * per GitHub org) simultaneously. A descriptor with no `github_org_login`
   * (pre-C / legacy single-org) keys as `github:__default`. A plain `github`
   * alias entry is ALSO maintained from the FIRST github entry for back-compat
   * with consumers that read `providers.github` directly
   * (`getActiveGithubCredential`). Non-github providers stay keyed by bare
   * provider name (`slack`, `discord`, `openrouter`, …).
   */
  providers?: Record<string, ProviderCredEntry>;
}

export interface ReadResult {
  store: CredentialStore | null;
  reason?: 'missing' | 'malformed' | 'wrong_permissions';
}

export function readCredentialStore(path = credentialStorePath()): ReadResult {
  if (!existsSync(path)) return { store: null, reason: 'missing' };

  if (platform() !== 'win32') {
    try {
      const stat = statSync(path);
      if ((stat.mode & 0o777) !== 0o600) {
        return { store: null, reason: 'wrong_permissions' };
      }
    } catch {
      return { store: null, reason: 'missing' };
    }
  }

  let raw: string;
  try {
    raw = readFileSync(path, 'utf-8');
  } catch {
    return { store: null, reason: 'missing' };
  }

  try {
    const parsed = JSON.parse(raw) as CredentialStore;

    // Always-required fields: identity + server URL.
    if (
      typeof parsed.agentId !== 'string' ||
      typeof parsed.agentSecret !== 'string' ||
      typeof parsed.spellguardBaseUrl !== 'string'
    ) {
      return { store: null, reason: 'malformed' };
    }

    // CR-002: a provider-agnostic store carries an explicit `providers`
    // field (possibly empty). The legacy path — where bootstrap delivered a
    // GitHub credential as part of identity — required `scopedToken` etc.
    // here. With bootstrap decoupled from any provider, an empty
    // `providers: {}` is a valid first-run state: identity is bootstrapped,
    // credentials arrive later via separate `credential_delivered` frames.
    const hasProvidersField =
      parsed.providers !== undefined &&
      typeof parsed.providers === 'object' &&
      parsed.providers !== null;

    if (!hasProvidersField) {
      // Legacy path: require the single-provider GitHub-shaped fields.
      if (
        typeof parsed.scopedToken !== 'string' ||
        typeof parsed.scopedTokenId !== 'string' ||
        typeof parsed.expiresAt !== 'string'
      ) {
        return { store: null, reason: 'malformed' };
      }

      // CR-011: validate `scopeSummary.repos` is an array of strings. Downstream
      // code (credential-consumer → tools.ts, the setup CLI) calls `.join`/
      // `.length` on this without a recovery path, so a partially-written or
      // corrupted store with `scopeSummary: null` or `repos: [123, null]` would
      // crash the agent at use time rather than be rejected at load time.
      const scope = (parsed as { scopeSummary?: unknown }).scopeSummary;
      if (typeof scope !== 'object' || scope === null) {
        return { store: null, reason: 'malformed' };
      }
      const repos = (scope as { repos?: unknown }).repos;
      if (!Array.isArray(repos) || repos.some((v) => typeof v !== 'string')) {
        return { store: null, reason: 'malformed' };
      }

      // Back-compat shim: synthesise a `providers.github` entry from legacy fields
      // so callers can always use the provider-agnostic map going forward.
      if (
        (!parsed.providers || Object.keys(parsed.providers).length === 0) &&
        parsed.scopedToken &&
        parsed.scopedTokenId
      ) {
        parsed.providers = {
          github: {
            kind: 'issued',
            credentialId: parsed.scopedTokenId,
            secrets: {},
            scopedToken: parsed.scopedToken,
            scopedTokenId: parsed.scopedTokenId,
            expiresAt: parsed.expiresAt,
            scopeSummary: parsed.scopeSummary,
            gitAuthorName: parsed.gitAuthorName,
            gitAuthorEmail: parsed.gitAuthorEmail,
            revoked: parsed.revoked,
          },
        };
      }
    }

    parsed.providers = parsed.providers ?? {};

    return { store: parsed };
  } catch {
    return { store: null, reason: 'malformed' };
  }
}

/**
 * Symlink-safe atomic write of a JSON store file.
 *
 * Threat model: a same-user adversary (compromised sibling plugin, malicious
 * npm postinstall, sidecar sharing `$HOME`) pre-places `path` as a symlink
 * pointing at a sensitive file owned by the same user (`~/.ssh/authorized_keys`,
 * `~/.bashrc`, etc.). A naive `openSync(path, 'w', 0o600)` follows the symlink
 * and truncates / overwrites the target.
 *
 * Defenses:
 *   1. `lstatSync(path)` before write — if the target is already a symlink,
 *      refuse with a clear error rather than touching anything. `lstatSync`
 *      does NOT dereference a symlink, so `isSymbolicLink()` is true even if
 *      the symlink dangles. ENOENT (the file doesn't exist yet) is fine —
 *      anything else (EACCES, ELOOP, the symlink-refusal we throw) propagates.
 *   2. Write to a temp sibling in the same directory, opened with
 *      `O_NOFOLLOW | O_EXCL | O_WRONLY | O_CREAT` — `O_EXCL` defeats a TOCTOU
 *      race where the attacker plants the temp path between lstat and open;
 *      `O_NOFOLLOW` defeats a symlink at the temp path itself. The temp
 *      filename uses `randomBytes(8)` for entropy so a same-user attacker
 *      polling the directory cannot reliably pre-create the path and cause
 *      `O_EXCL` to fail (a DoS-availability concern; security is intact).
 *   3. `fchmodSync(fd, 0o600)` after open — `openSync`'s mode arg only applies
 *      on create, so if the target ever pre-exists with a looser mode the bits
 *      must be reasserted on the fd. Doing it on the fd (not by path) avoids
 *      a window where the file is readable.
 *   4. `fsyncSync(fd)` before close — durability for the byte payload.
 *   5. `renameSync(tmp, target)` — atomic on POSIX. The rename does NOT follow
 *      a symlink at the target; it replaces the symlink with the regular file.
 *      Combined with the lstat check this means an attacker who races a symlink
 *      in after our lstat will at worst cause the rename to swap their symlink
 *      out for our credential file — they never get their target overwritten.
 *
 * On Windows we fall back to `writeFileSync` (POSIX bits don't apply; symlink
 * pre-placement requires elevated permissions in typical deployments).
 */
// biome-ignore lint/complexity/noExcessiveCognitiveComplexity: atomic write needs all steps in one function to maintain the lstat→open→fchmod→fsync→rename invariant
function atomicWriteJsonStore(path: string, store: CredentialStore): void {
  mkdirSync(dirname(path), { recursive: true, mode: 0o700 });
  const content = JSON.stringify(store, null, 2);

  if (platform() === 'win32') {
    // Windows: no POSIX bits; rely on directory ACLs. `O_NOFOLLOW` is not
    // meaningful here and would error on the `openSync` call.
    writeFileSync(path, content, 'utf-8');
    return;
  }

  // Refuse to follow a symlink at `path`.
  let lst: ReturnType<typeof lstatSync> | null = null;
  try {
    lst = lstatSync(path);
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err;
  }
  if (lst?.isSymbolicLink()) {
    throw new Error(
      `credential store path is a symlink — refusing to follow: ${path}`,
    );
  }

  const tmpPath = join(
    dirname(path),
    `.${basename(path)}.tmp.${randomBytes(8).toString('hex')}`,
  );

  const flags =
    fsConstants.O_WRONLY |
    fsConstants.O_CREAT |
    fsConstants.O_EXCL |
    fsConstants.O_NOFOLLOW;

  let fd: number | null = null;
  try {
    fd = openSync(tmpPath, flags, 0o600);
    // Reassert mode on the fd: `openSync`'s mode arg only applies on create,
    // so if the temp path was a pre-existing file with a looser mode (which
    // O_EXCL should have prevented, but belt-and-suspenders), this fixes it.
    fchmodSync(fd, 0o600);
    writeSync(fd, content, 0, 'utf-8');
    fsyncSync(fd);
  } catch (err) {
    if (fd !== null) {
      try {
        closeSync(fd);
      } catch {
        // ignore
      }
      fd = null;
    }
    // Best-effort cleanup of the temp file. If it doesn't exist, ignore.
    try {
      unlinkSync(tmpPath);
    } catch {
      // ignore
    }
    throw err;
  }
  // Close the fd before rename so any platform that fusses about open fds
  // during rename is satisfied. Rename is atomic on POSIX.
  closeSync(fd);
  fd = null;

  try {
    renameSync(tmpPath, path);
  } catch (err) {
    try {
      unlinkSync(tmpPath);
    } catch {
      // ignore
    }
    throw err;
  }
}

export function writeCredentialStore(
  store: CredentialStore,
  path = credentialStorePath(),
): void {
  atomicWriteJsonStore(path, store);
}

export function markRevoked(path = credentialStorePath()): void {
  const r = readCredentialStore(path);
  if (r.store) atomicWriteJsonStore(path, { ...r.store, revoked: true });
}

export function updateLastServerSeq(
  seq: string,
  path = credentialStorePath(),
): void {
  const r = readCredentialStore(path);
  if (r.store) atomicWriteJsonStore(path, { ...r.store, lastServerSeq: seq });
}

/**
 * Persist the cached known-credentials projection so the next restart's
 * reconnect Resume echoes the real set instead of `[]`. Read-modify-write,
 * mirroring updateLastServerSeq. Without this the broker's divergence
 * detector re-delivers every credential on each reconnect (double-restart).
 */
export function updateKnownCredentials(
  known: Array<{ provider: string; scoped_token_id: string }>,
  path = credentialStorePath(),
): void {
  const r = readCredentialStore(path);
  if (r.store)
    atomicWriteJsonStore(path, { ...r.store, knownCredentials: known });
}
